// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pharmacare.Data;

#nullable disable

namespace Pharmacare.Api.Migrations
{
    [DbContext(typeof(PharmacareDbContext))]
    [Migration("20220607184323_InsertData")]
    partial class InsertData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Pharmacare.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pharmacare.Entities.ActiveSubstance", b =>
                {
                    b.Property<int>("SubstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubstanceId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternationalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubstanceId");

                    b.ToTable("ActiveSubstances");

                    b.HasData(
                        new
                        {
                            SubstanceId = 1,
                            Description = "Opis",
                            InternationalName = "Amoxicillin clavulanate",
                            Name = "Kwas klawulanowy"
                        },
                        new
                        {
                            SubstanceId = 2,
                            Description = "Opis",
                            InternationalName = "Beclometasone",
                            Name = "Dipropionian beklometazonu"
                        },
                        new
                        {
                            SubstanceId = 3,
                            Description = "Opis",
                            InternationalName = "Clarithromycin",
                            Name = "Klarytromycyna"
                        },
                        new
                        {
                            SubstanceId = 4,
                            Description = "Opis",
                            InternationalName = "Amoxicillin",
                            Name = "Amoksycylina"
                        },
                        new
                        {
                            SubstanceId = 5,
                            Description = "Opis",
                            InternationalName = "Salbutamol",
                            Name = "Salbutamol"
                        },
                        new
                        {
                            SubstanceId = 6,
                            Description = "Opis",
                            InternationalName = "Cefixime",
                            Name = "Cefiksym"
                        },
                        new
                        {
                            SubstanceId = 7,
                            Description = "Opis",
                            InternationalName = "Azithromycin",
                            Name = "Azytromycyna"
                        },
                        new
                        {
                            SubstanceId = 8,
                            Description = "Opis",
                            InternationalName = "Betametasone",
                            Name = "Betametazon"
                        },
                        new
                        {
                            SubstanceId = 9,
                            Description = "Opis",
                            InternationalName = "Cefaclor",
                            Name = "Cefaklor"
                        },
                        new
                        {
                            SubstanceId = 10,
                            Description = "Opis",
                            InternationalName = "Cetirizine",
                            Name = "Cetyryzyna"
                        });
                });

            modelBuilder.Entity("Pharmacare.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserGuid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserGuid = 1
                        },
                        new
                        {
                            Id = 2,
                            UserGuid = 2
                        });
                });

            modelBuilder.Entity("Pharmacare.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Pharmacare.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ból"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dla diabetyków"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dermatologia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Homeopatia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Układ krążenia"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Odporność"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Przeziębienie i grypa"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Zdrowie mężczyny"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Seks i antykoncepcja"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Alergia"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Układ pokarmowy"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Układ mięśniowo-szkieletowy"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Oczy"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Układ moczowo-płciowy"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Układ nerwowy"
                        });
                });

            modelBuilder.Entity("Pharmacare.Entities.Drug", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugId"), 1L, 1);

                    b.Property<int>("ActiveSubstanceId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrugId");

                    b.ToTable("Drugs");

                    b.HasData(
                        new
                        {
                            DrugId = 1,
                            ActiveSubstanceId = 5,
                            CategoryId = 0,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "50 tabletek",
                            Price = 31.99m,
                            Quantity = 59,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 2,
                            ActiveSubstanceId = 4,
                            CategoryId = 0,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "75 tabletek",
                            Price = 70.99m,
                            Quantity = 165,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 3,
                            ActiveSubstanceId = 9,
                            CategoryId = 0,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "100 tabletek",
                            Price = 39.99m,
                            Quantity = 857,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 4,
                            ActiveSubstanceId = 7,
                            CategoryId = 0,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "20 tabletek",
                            Price = 62.99m,
                            Quantity = 225,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 5,
                            ActiveSubstanceId = 3,
                            CategoryId = 0,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "20 tabletek",
                            Price = 117.99m,
                            Quantity = 853,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 6,
                            ActiveSubstanceId = 2,
                            CategoryId = 1,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "75 tabletek",
                            Price = 49.99m,
                            Quantity = 671,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 7,
                            ActiveSubstanceId = 9,
                            CategoryId = 1,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "10 tabletek",
                            Price = 63.99m,
                            Quantity = 724,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 8,
                            ActiveSubstanceId = 0,
                            CategoryId = 1,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "10 tabletek",
                            Price = 32.99m,
                            Quantity = 90,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 9,
                            ActiveSubstanceId = 2,
                            CategoryId = 1,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "150 tabletek",
                            Price = 149.99m,
                            Quantity = 808,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 10,
                            ActiveSubstanceId = 6,
                            CategoryId = 1,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "10 tabletek",
                            Price = 74.99m,
                            Quantity = 871,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 11,
                            ActiveSubstanceId = 5,
                            CategoryId = 2,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "50 tabletek",
                            Price = 79.99m,
                            Quantity = 616,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 12,
                            ActiveSubstanceId = 7,
                            CategoryId = 2,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "75 tabletek",
                            Price = 60.99m,
                            Quantity = 341,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 13,
                            ActiveSubstanceId = 6,
                            CategoryId = 2,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "150 tabletek",
                            Price = 62.99m,
                            Quantity = 96,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 14,
                            ActiveSubstanceId = 7,
                            CategoryId = 2,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "50 tabletek",
                            Price = 137.99m,
                            Quantity = 92,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 15,
                            ActiveSubstanceId = 8,
                            CategoryId = 2,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "100 tabletek",
                            Price = 57.99m,
                            Quantity = 855,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 16,
                            ActiveSubstanceId = 1,
                            CategoryId = 3,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "20 tabletek",
                            Price = 27.99m,
                            Quantity = 543,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 17,
                            ActiveSubstanceId = 1,
                            CategoryId = 3,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "50 tabletek",
                            Price = 32.99m,
                            Quantity = 861,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 18,
                            ActiveSubstanceId = 2,
                            CategoryId = 3,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "20 tabletek",
                            Price = 76.99m,
                            Quantity = 942,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 19,
                            ActiveSubstanceId = 4,
                            CategoryId = 3,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "150 tabletek",
                            Price = 120.99m,
                            Quantity = 390,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 20,
                            ActiveSubstanceId = 7,
                            CategoryId = 3,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "200 tabletek",
                            Price = 115.99m,
                            Quantity = 688,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 21,
                            ActiveSubstanceId = 5,
                            CategoryId = 4,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "100 tabletek",
                            Price = 149.99m,
                            Quantity = 569,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 22,
                            ActiveSubstanceId = 3,
                            CategoryId = 4,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "75 tabletek",
                            Price = 106.99m,
                            Quantity = 130,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 23,
                            ActiveSubstanceId = 9,
                            CategoryId = 4,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "50 tabletek",
                            Price = 138.99m,
                            Quantity = 625,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 24,
                            ActiveSubstanceId = 0,
                            CategoryId = 4,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "200 tabletek",
                            Price = 122.99m,
                            Quantity = 123,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 25,
                            ActiveSubstanceId = 3,
                            CategoryId = 4,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "10 tabletek",
                            Price = 98.99m,
                            Quantity = 388,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 26,
                            ActiveSubstanceId = 7,
                            CategoryId = 5,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "30 tabletek",
                            Price = 105.99m,
                            Quantity = 145,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 27,
                            ActiveSubstanceId = 6,
                            CategoryId = 5,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "200 tabletek",
                            Price = 24.99m,
                            Quantity = 552,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 28,
                            ActiveSubstanceId = 1,
                            CategoryId = 5,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "75 tabletek",
                            Price = 97.99m,
                            Quantity = 502,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 29,
                            ActiveSubstanceId = 9,
                            CategoryId = 5,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "50 tabletek",
                            Price = 59.99m,
                            Quantity = 907,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 30,
                            ActiveSubstanceId = 2,
                            CategoryId = 5,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "75 tabletek",
                            Price = 57.99m,
                            Quantity = 794,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 31,
                            ActiveSubstanceId = 3,
                            CategoryId = 6,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "200 tabletek",
                            Price = 59.99m,
                            Quantity = 83,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 32,
                            ActiveSubstanceId = 1,
                            CategoryId = 6,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "150 tabletek",
                            Price = 22.99m,
                            Quantity = 534,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 33,
                            ActiveSubstanceId = 5,
                            CategoryId = 6,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "10 tabletek",
                            Price = 121.99m,
                            Quantity = 134,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 34,
                            ActiveSubstanceId = 0,
                            CategoryId = 6,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "150 tabletek",
                            Price = 96.99m,
                            Quantity = 395,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 35,
                            ActiveSubstanceId = 6,
                            CategoryId = 6,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "75 tabletek",
                            Price = 97.99m,
                            Quantity = 525,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 36,
                            ActiveSubstanceId = 6,
                            CategoryId = 7,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "200 tabletek",
                            Price = 72.99m,
                            Quantity = 899,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 37,
                            ActiveSubstanceId = 2,
                            CategoryId = 7,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "150 tabletek",
                            Price = 30.99m,
                            Quantity = 23,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 38,
                            ActiveSubstanceId = 8,
                            CategoryId = 7,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "30 tabletek",
                            Price = 24.99m,
                            Quantity = 194,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 39,
                            ActiveSubstanceId = 6,
                            CategoryId = 7,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "150 tabletek",
                            Price = 85.99m,
                            Quantity = 909,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 40,
                            ActiveSubstanceId = 2,
                            CategoryId = 7,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "200 tabletek",
                            Price = 106.99m,
                            Quantity = 912,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 41,
                            ActiveSubstanceId = 7,
                            CategoryId = 8,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "10 tabletek",
                            Price = 24.99m,
                            Quantity = 675,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 42,
                            ActiveSubstanceId = 0,
                            CategoryId = 8,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "150 tabletek",
                            Price = 98.99m,
                            Quantity = 913,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 43,
                            ActiveSubstanceId = 5,
                            CategoryId = 8,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "150 tabletek",
                            Price = 91.99m,
                            Quantity = 263,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 44,
                            ActiveSubstanceId = 7,
                            CategoryId = 8,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "75 tabletek",
                            Price = 20.99m,
                            Quantity = 861,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 45,
                            ActiveSubstanceId = 0,
                            CategoryId = 8,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "200 tabletek",
                            Price = 95.99m,
                            Quantity = 289,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 46,
                            ActiveSubstanceId = 7,
                            CategoryId = 9,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "200 tabletek",
                            Price = 53.99m,
                            Quantity = 331,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 47,
                            ActiveSubstanceId = 2,
                            CategoryId = 9,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "50 tabletek",
                            Price = 63.99m,
                            Quantity = 268,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 48,
                            ActiveSubstanceId = 5,
                            CategoryId = 9,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "30 tabletek",
                            Price = 58.99m,
                            Quantity = 933,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 49,
                            ActiveSubstanceId = 2,
                            CategoryId = 9,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "150 tabletek",
                            Price = 73.99m,
                            Quantity = 274,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 50,
                            ActiveSubstanceId = 5,
                            CategoryId = 9,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "30 tabletek",
                            Price = 112.99m,
                            Quantity = 553,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 51,
                            ActiveSubstanceId = 7,
                            CategoryId = 10,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "75 tabletek",
                            Price = 145.99m,
                            Quantity = 341,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 52,
                            ActiveSubstanceId = 7,
                            CategoryId = 10,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "30 tabletek",
                            Price = 123.99m,
                            Quantity = 71,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 53,
                            ActiveSubstanceId = 2,
                            CategoryId = 10,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "20 tabletek",
                            Price = 126.99m,
                            Quantity = 293,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 54,
                            ActiveSubstanceId = 9,
                            CategoryId = 10,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "200 tabletek",
                            Price = 19.99m,
                            Quantity = 849,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 55,
                            ActiveSubstanceId = 9,
                            CategoryId = 10,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "50 tabletek",
                            Price = 43.99m,
                            Quantity = 286,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 56,
                            ActiveSubstanceId = 7,
                            CategoryId = 11,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "200 tabletek",
                            Price = 19.99m,
                            Quantity = 654,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 57,
                            ActiveSubstanceId = 0,
                            CategoryId = 11,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "50 tabletek",
                            Price = 55.99m,
                            Quantity = 375,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 58,
                            ActiveSubstanceId = 9,
                            CategoryId = 11,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "50 tabletek",
                            Price = 144.99m,
                            Quantity = 767,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 59,
                            ActiveSubstanceId = 7,
                            CategoryId = 11,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "30 tabletek",
                            Price = 133.99m,
                            Quantity = 869,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 60,
                            ActiveSubstanceId = 6,
                            CategoryId = 11,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "30 tabletek",
                            Price = 51.99m,
                            Quantity = 253,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 61,
                            ActiveSubstanceId = 2,
                            CategoryId = 12,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "50 tabletek",
                            Price = 136.99m,
                            Quantity = 475,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 62,
                            ActiveSubstanceId = 4,
                            CategoryId = 12,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "30 tabletek",
                            Price = 119.99m,
                            Quantity = 116,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 63,
                            ActiveSubstanceId = 7,
                            CategoryId = 12,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "150 tabletek",
                            Price = 21.99m,
                            Quantity = 329,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 64,
                            ActiveSubstanceId = 1,
                            CategoryId = 12,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "10 tabletek",
                            Price = 48.99m,
                            Quantity = 749,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 65,
                            ActiveSubstanceId = 1,
                            CategoryId = 12,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "75 tabletek",
                            Price = 98.99m,
                            Quantity = 458,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 66,
                            ActiveSubstanceId = 4,
                            CategoryId = 13,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "10 tabletek",
                            Price = 102.99m,
                            Quantity = 912,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 67,
                            ActiveSubstanceId = 7,
                            CategoryId = 13,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "100 tabletek",
                            Price = 98.99m,
                            Quantity = 51,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 68,
                            ActiveSubstanceId = 9,
                            CategoryId = 13,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "30 tabletek",
                            Price = 71.99m,
                            Quantity = 87,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 69,
                            ActiveSubstanceId = 5,
                            CategoryId = 13,
                            Dosage = "1 tabletka",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "100 tabletek",
                            Price = 146.99m,
                            Quantity = 197,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 70,
                            ActiveSubstanceId = 8,
                            CategoryId = 13,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "150 tabletek",
                            Price = 129.99m,
                            Quantity = 499,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 71,
                            ActiveSubstanceId = 7,
                            CategoryId = 14,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "50 tabletek",
                            Price = 41.99m,
                            Quantity = 565,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 72,
                            ActiveSubstanceId = 5,
                            CategoryId = 14,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "100 tabletek",
                            Price = 64.99m,
                            Quantity = 212,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 73,
                            ActiveSubstanceId = 6,
                            CategoryId = 14,
                            Dosage = "3 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "100 tabletek",
                            Price = 78.99m,
                            Quantity = 735,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 74,
                            ActiveSubstanceId = 4,
                            CategoryId = 14,
                            Dosage = "2 tabletki",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "30 tabletek",
                            Price = 110.99m,
                            Quantity = 158,
                            TradeName = "Nazwa leku"
                        },
                        new
                        {
                            DrugId = 75,
                            ActiveSubstanceId = 8,
                            CategoryId = 14,
                            Dosage = "5 tabletek",
                            ImageURL = "https://www.sennik.biz//o/l/z/w336/lzndk3ruq8xh.jpg",
                            PackSize = "10 tabletek",
                            Price = 96.99m,
                            Quantity = 872,
                            TradeName = "Nazwa leku"
                        });
                });

            modelBuilder.Entity("Pharmacare.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Pharmacare.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
